<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars($shop['name']) ?> Dashboard</title><link rel="stylesheet" href="view/css/dashboard.css?v=2"></head>
<body>
<header><div class="brand-wrapper"><div class="brand-icon">OW</div><h1><?= htmlspecialchars($shop['name']) ?></h1></div><div class="user-badge"><span>Shop Owner</span><a href="account.php">Profile</a><a href="index.php?logout=1">Log out</a></div></header>
<main><div class="page-heading"><h2>Owner dashboard</h2><p>Manage your shop, inventory, and staff.</p></div>
<?php if (!empty($message)): ?><div class="notice"><?= htmlspecialchars($message) ?></div><?php endif; ?><?php if (!empty($error)): ?><div class="error"><?= htmlspecialchars($error) ?></div><?php endif; ?>
<div class="owner-dashboard-layout">
	<aside class="owner-sidebar" aria-label="Owner dashboard sections">
		<button type="button" class="owner-nav-button active" data-panel="profile-panel">Shop Profile</button>
		<button type="button" class="owner-nav-button" data-panel="inventory-panel">Inventory</button>
		<button type="button" class="owner-nav-button" data-panel="staff-panel">Staff Management</button>
	</aside>
	<div class="owner-panels">
		<section id="profile-panel" class="owner-panel active"><h2>Shop profile</h2><p class="section-description">Update the public name of your shop.</p><form method="post"><label>Shop name<input name="shop_name" value="<?= htmlspecialchars($shop['name']) ?>" required></label><button name="update_shop">Save shop profile</button></form></section>
		<section id="inventory-panel" class="owner-panel"><h2>Products and inventory</h2><p class="section-description">Add products and keep stock levels current.</p><form method="post"><label>Product name<input name="name" required></label><label>Price<input name="price" type="number" min="0" step="0.01" required></label><label>Opening stock<input name="stock" type="number" min="0" required></label><button name="add_product">Add product</button></form><div class="table-wrapper"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody><?php foreach ($products as $product): ?><tr><td><?= htmlspecialchars($product['name']) ?></td><td>$<?= number_format((float) $product['price'], 2) ?></td><td><?= (int) $product['stock'] ?></td><td><form method="post" class="inline-form"><input type="hidden" name="product_id" value="<?= (int) $product['id'] ?>"><input name="stock_change" type="number" placeholder="+/-" required><button>Update stock</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
		<section id="staff-panel" class="owner-panel"><h2>Staff management</h2><p class="section-description">Create and remove staff accounts for this shop.</p><form method="post" action="controller/staffController.php"><input type="hidden" name="shop_id" value="<?= $shopId ?>"><label>Username<input name="username" required></label><label>Email<input name="email" type="email"></label><label>Temporary password<input name="password" type="password" minlength="6" required></label><button name="create_staff">Create staff account</button></form><?php if (!empty($staff)): ?><div class="table-wrapper"><table><thead><tr><th>Username</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach ($staff as $member): ?><tr><td><?= htmlspecialchars($member['username']) ?></td><td><?= htmlspecialchars($member['email'] ?? '') ?></td><td><?= htmlspecialchars($member['status']) ?></td><td><form method="post" action="controller/staffController.php"><input type="hidden" name="account_id" value="<?= (int) $member['id'] ?>"><button name="remove_staff">Remove</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
	</div>
</div>
</main><script>document.querySelectorAll('.owner-nav-button').forEach(function (button) { button.addEventListener('click', function () { document.querySelectorAll('.owner-nav-button').forEach(function (item) { item.classList.remove('active'); }); document.querySelectorAll('.owner-panel').forEach(function (panel) { panel.classList.remove('active'); }); button.classList.add('active'); document.getElementById(button.dataset.panel).classList.add('active'); }); });</script></body></html>
